[Icon Theme]
Name=Elysia
Comment=Icons worthy of Elysium
Inherits=hicolor
Example=folder
FollowsColorScheme=true

Directories=actions/16,actions/22,actions/24,actions/scalable,status/22,status/24,status/scalable,apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/96,apps/128,apps/256,apps/scalable,categories/16,categories/22,categories/24,categories/32,categories/48,categories/64,categories/96,categories/128,categories/256,categories/scalable,devices/16,devices/22,devices/24,devices/32,devices/48,devices/64,devices/128,devices/256,devices/scalable,emblems/16,emblems/22,emblems/24,emblems/32,emblems/48,emblems/64,emblems/96,emblems/128,emblems/256,emblems/scalable,mimetypes/16,mimetypes/22,mimetypes/24,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/96,mimetypes/128,mimetypes/256,mimetypes/scalable,places/16,places/22,places/24,places/32,places/48,places/64,places/128,places/256,places/scalable,animations/16,applets/22,applets/24,applets/scalable
[actions/16]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[actions/22]
Size=22
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[actions/24]
Size=24
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[actions/scalable]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[status/22]
Size=22
Context=Status
Type=Scalable
MinSize=8
MaxSize=512

[status/24]
Size=24
Context=Status
Type=Scalable
MinSize=8
MaxSize=512

[status/scalable]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=512

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/22]
Size=22
Context=Applications
Type=Fixed

[apps/24]
Size=24
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Fixed

[apps/64]
Size=64
Context=Applications
Type=Fixed

[apps/96]
Size=96
Context=Applications
Type=Scalable
MinSize=56
MaxSize=512

[apps/128]
Size=128
Context=Applications
Type=Fixed

[apps/256]
Size=256
Context=Applications
Type=Fixed

[apps/scalable]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512

[categories/16]
Size=16
Context=Categories
Type=Fixed

[categories/22]
Size=22
Context=Categories
Type=Fixed

[categories/24]
Size=24
Context=Categories
Type=Fixed

[categories/32]
Size=32
Context=Categories
Type=Fixed

[categories/48]
Size=48
Context=Categories
Type=Fixed

[categories/64]
Size=64
Context=Categories
Type=Fixed

[categories/96]
Size=96
Context=Categories
Type=Scalable
MinSize=56
MaxSize=512

[categories/128]
Size=128
Context=Categories
Type=Fixed

[categories/256]
Size=256
Context=Categories
Type=Fixed

[categories/scalable]
Size=16
Context=Categories
Type=Scalable
MinSize=8
MaxSize=512

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/22]
Size=22
Context=Devices
Type=Fixed

[devices/24]
Size=24
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[devices/48]
Size=48
Context=Devices
Type=Fixed

[devices/64]
Size=64
Context=Devices
Type=Fixed

[devices/128]
Size=128
Context=Devices
Type=Fixed

[devices/256]
Size=256
Context=Devices
Type=Fixed

[devices/scalable]
Size=16
Context=Devices
Type=Scalable
MinSize=8
MaxSize=512

[emblems/16]
Size=16
Context=Emblems
Type=Fixed

[emblems/22]
Size=22
Context=Emblems
Type=Fixed

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[emblems/32]
Size=32
Context=Emblems
Type=Fixed

[emblems/48]
Size=48
Context=Emblems
Type=Fixed

[emblems/64]
Size=64
Context=Emblems
Type=Fixed

[emblems/96]
Size=96
Context=Emblems
Type=Scalable
MinSize=56
MaxSize=512

[emblems/128]
Size=128
Context=Emblems
Type=Fixed

[emblems/256]
Size=256
Context=Emblems
Type=Fixed

[emblems/scalable]
Size=16
Context=Emblems
Type=Scalable
MinSize=8
MaxSize=512

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Fixed

[mimetypes/24]
Size=24
Context=MimeTypes
Type=Fixed

[mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

[mimetypes/48]
Size=48
Context=MimeTypes
Type=Fixed

[mimetypes/64]
Size=64
Context=MimeTypes
Type=Fixed

[mimetypes/96]
Size=96
Context=MimeTypes
Type=Scalable
MinSize=56
MaxSize=512

[mimetypes/128]
Size=128
Context=MimeTypes
Type=Fixed

[mimetypes/256]
Size=256
Context=MimeTypes
Type=Fixed

[mimetypes/scalable]
Size=16
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=256

[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/128]
Size=128
Context=Places
Type=Fixed

[places/256]
Size=256
Context=Places
Type=Fixed

[places/scalable]
Size=16
Context=Places
Type=Scalable
MinSize=8
MaxSize=512

[animations/16]
Size=16
Context=Animations
Type=Fixed

[applets/22]
Size=22
Context=Applications
Type=Fixed

[applets/24]
Size=24
Context=Applications
Type=Fixed

[applets/scalable]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512
